#  This file is included to make running ansible from command line directly an easier process. Not needed by Vagrant.
#     Usage: $ ansible-playbook main.yml -u {{ vmuser1 }}
#            $ ansible-playbook main.yml -i inv_rocky.ini -u {{ vmuser1 }}
[debian]
10.0.2.15

[all:children]
debian

